### PR TITLE
fix(pasaport): set auth cookies to root domain

### LINKED ISSUE #507: bug(pasaport): cookies are not carried over to apps other than pasaport
### Describe the bug
When we want to login through https://pasaport.dev.kamp.us/auth/signin it works correctly but the cookie is only set for postaci, which means other applications don't have access to it.

Figure out a way to do this with our next-auth setup.

### Steps to reproduce the behavior
1. go to https://pasaport.dev.kamp.us/auth/signin
2. login via any provider
3. when it redirects back to pasaport (you're gonna see a 404 page, and it's ok, just open the devtools and check the cookie) 
4. then navigate to https://dev.kamp.us
5. you should see login button instead of session user information

### Expected behavior
When i navigate to https://dev.kamp.us at step 4, i should see the loggedin user's session information as a JSON string (step 5)

### PR DESCRIPTION
**Pull request by FurkanGM**
Closes #507 💯

### CODE REVIEW

File: packages/next-auth/lib/env.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { parseEnv, z } from "znv";
 
 export const env = parseEnv(
   {
+    AUTH_COOKIE_DOMAIN: process.env.COOKIE_DOMAIN,
```
Comment (usirin) [inline packages/next-auth/lib/env.ts]: we have to add this to `turbo.json`

**Review by usirin — CHANGES_REQUESTED** [review]

**Review by usirin — APPROVED** [review]
💯
